---
# This playbook will run flood.py on the target host.
- hosts: all
  remote_user: root
  vars:
    SATELLITE_HOST: changeme
    CONTENT_HOST_PREFIX: changeme
    ACTIVATION_KEY: changeme
    NUMBER_OF_HOSTS: changeme
    EXIT_CRITERIA: changeme
    RHSM_LOG_DIR: /content-host-d
  tasks:
  - name: Run flood.py command
    command: "python /content-host-d/flood.py --satellite {{ SATELLITE_HOST }} --name {{ CONTENT_HOST_PREFIX }} --key {{ ACTIVATION_KEY }} --count {{ NUMBER_OF_HOSTS }} --exit-criteria {{ EXIT_CRITERIA }} --rhsm-log-dir {{ RHSM_LOG_DIR }}"
